wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.15
    start_time: 1676546939.918872
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.8.15
      5: 0.13.10
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 32
except_ratios:
  desc: null
  value: '[[1, 2], [2, 1], [2, 2], [1, 3], [3, 1], [3, 3], [1, 4], [2, 4], [4, 1],
    [4, 2], [4, 4]]'
parts_num_per_ratio:
  desc: null
  value: 240
scale_ratios:
  desc: null
  value: '[1, 2, 3]'
seriesnum:
  desc: null
  value: 1000
valid_max_len:
  desc: null
  value: 10
valida_batch_size:
  desc: null
  value: 1
